---

# Install common dependencies
- name: Install dependencies
  package:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ packages }}"
  tags:
    - common

# Install specific dependencies
- name: Portal dependencies
  package:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ portal.packages }}"
  tags:
    - portal

# Create apache2 service
- name: Enable apache2 service
  service:
    name: apache2
    state: started
    enabled: yes
  tags:
    - common

# Create common directories
- name: Creates directories
  file:
    path: "{{ item.path }}"
    state: directory
  with_items:
    - "{{ directories }}"
  tags:
    - common

# Create specific directories
- name: Portal directories
  file:
    path: "{{ item.path }}"
    state: directory
  with_items:
    - "{{ portal.directories }}"
  tags:
    - portal

- name: Wordpress directories
  file:
    path: "{{ item.path }}"
    state: directory
  with_items:
    - "{{ wordpress.directories }}"
  tags:
    - wordpress

- name: Moodle directories
  file:
    path: "{{ item.path }}"
    state: directory
  with_items:
    - "{{ moodle.directories }}"
  tags:
    - moodle

# Config apache
- name: Enable mod_rewrite
  apache2_module:
    name: rewrite
    state: present
  notify:
    - restart apache
  tags:
    - common
- name: Conf fqdn
  copy:
    content: "ServerName localhost"
    dest: /etc/apache2/conf-available/fqdn.conf
  tags:
    - common
- name: Enable a2enconf
  command: a2enconf {{ item }}
  with_items:
    - fqdn
  notify:
    - restart apache
  tags:
    - common

# VH config
- name: Create Portal virtual hosts config
  template:
    src: templates/vh.portal.conf.j2
    dest: /etc/apache2/sites-available/agora.conf
  notify:
    - restart apache
  tags:
    - portal

- name: Create Wordpress/Moodle virtual hosts config
  template:
    src: templates/vh.conf.j2
    dest: /etc/apache2/sites-available/agora.conf
  notify:
    - restart apache
  tags: [wordpress, moodle]

- name: Remove default config
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify:
    - restart apache
  tags:
    - common

- name: Create symbolic link
  file:
    src: /etc/apache2/sites-available/agora.conf
    dest: /etc/apache2/sites-enabled/agora.conf
    state: link
  notify:
    - restart apache
  tags:
    - common

# Config php
- name: Config php
  command: >
    {{ item }}
  args:
      warn: false
  with_items:
    - "{{ php.commands }}"
  notify:
    - restart apache
  tags:
    - common

# Config opcache
- name: Config opcache
  command: >
    {{ item }}
  args:
      warn: false
  with_items:
    - "{{ opcache.commands }}"
  notify:
    - restart apache
  tags:
    - common
